import { Users, Award, TrendingUp, Star, Trophy, BadgeCheck, Target } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import RecognitionBadge from "@/components/affiliate/RecognitionBadge";

const AffiliateTermsPage = () => {
  // Sample recognition badges
  const recognitionBadges = [
    {
      id: "founder-partner",
      title: "Founding Infrastructure Partner",
      description: "Awarded to early affiliates who contribute to building the ecosystem",
      icon: <Star className="h-5 w-5 text-yellow-500" />,
      status: "active" as const
    },
    {
      id: "community-builder",
      title: "Community Builder",
      description: "Earned by affiliates with 10+ active referrals",
      icon: <Users className="h-5 w-5 text-blue-500" />,
      status: "active" as const
    },
    {
      id: "rising-star",
      title: "Rising Star",
      description: "First 5 referrals that become active customers",
      icon: <TrendingUp className="h-5 w-5 text-green-500" />,
      status: "pending" as const
    },
    {
      id: "top-earner",
      title: "Top Earner",
      description: "Awarded to affiliates with highest monthly earnings",
      icon: <Trophy className="h-5 w-5 text-purple-500" />,
      status: "inactive" as const
    },
    {
      id: "ambassador",
      title: "Infrastructure Ambassador",
      description: "Recognized for exceptional contribution to builder community",
      icon: <BadgeCheck className="h-5 w-5 text-red-500" />,
      status: "inactive" as const
    }
  ];

  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8">
        <h1 className="text-2xl font-bold dark:text-white">Affiliate Program Terms</h1>
        <p className="text-gray-600 dark:text-gray-400">
          Understanding your role as a builder promoting infrastructure to other builders
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          <Card>
            <CardHeader>
              <CardTitle className="text-xl dark:text-white">Program Overview</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                The Tonstores Affiliate Program is designed for builders who understand the importance 
                of infrastructure independence. As an affiliate, you're not just earning commissions 
                – you're building the ecosystem alongside us.
              </p>
              <p className="text-gray-700 dark:text-gray-300">
                Your role is to advocate for infrastructure solutions that prioritize builder autonomy, 
                data ownership, and independence from exploitative platforms.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-xl dark:text-white">Commission Structure</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="border dark:border-gray-700 rounded-lg p-4">
                  <h3 className="font-medium dark:text-white mb-2">Recurring Commission</h3>
                  <p className="text-2xl font-bold text-Tonstores-green mb-1">20%</p>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    On all revenue generated by your referrals for as long as they remain customers
                  </p>
                </div>
                
                <div className="border dark:border-gray-700 rounded-lg p-4">
                  <h3 className="font-medium dark:text-white mb-2">Bonus Structure</h3>
                  <p className="text-2xl font-bold text-Tonstores-green mb-1">Up to 30%</p>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    For affiliates who reach specific milestones in referrals and earnings
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-xl dark:text-white">Terms & Conditions</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h3 className="font-medium dark:text-white mb-2">Eligibility</h3>
                  <ul className="list-disc pl-5 space-y-2 text-gray-700 dark:text-gray-300">
                    <li>You must be an active Tonstores customer in good standing</li>
                    <li>You must complete the affiliate application and approval process</li>
                    <li>You agree to represent Tonstores accurately and ethically</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-medium dark:text-white mb-2">Payment</h3>
                  <ul className="list-disc pl-5 space-y-2 text-gray-700 dark:text-gray-300">
                    <li>Commissions are paid monthly, provided earnings reach ₦5,000 or more</li>
                    <li>Unpaid commissions roll over to the following month</li>
                    <li>Payments are processed by the 15th of the following month</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-medium dark:text-white mb-2">Prohibited Activities</h3>
                  <ul className="list-disc pl-5 space-y-2 text-gray-700 dark:text-gray-300">
                    <li>Spamming or unsolicited promotional activities</li>
                    <li>Misrepresenting Tonstores features or benefits</li>
                    <li>Creating fake accounts to manipulate referrals</li>
                    <li>Using trademarked terms in domain names or misleading advertising</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-xl dark:text-white">Affiliate Principles</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-start">
                  <div className="bg-Tonstores-green/10 rounded-full p-2 mr-3 mt-0.5">
                    <Target className="h-5 w-5 text-Tonstores-green" />
                  </div>
                  <div>
                    <h3 className="font-medium dark:text-white">Shared Success</h3>
                    <p className="text-gray-700 dark:text-gray-300">
                      Frame your promotion around shared success: "When you help another Builder 
                      professionalize, we all benefit – you through commission, them through better 
                      infrastructure, all of us through a stronger community of professional Builders 
                      who aren't dependent on exploitative platforms."
                    </p>
                  </div>
                </div>

                <div className="flex items-start">
                  <div className="bg-Tonstores-green/10 rounded-full p-2 mr-3 mt-0.5">
                    <Users className="h-5 w-5 text-Tonstores-green" />
                  </div>
                  <div>
                    <h3 className="font-medium dark:text-white">Builder-to-Builder Approach</h3>
                    <p className="text-gray-700 dark:text-gray-300">
                      Position yourself as a fellow builder sharing a solution, not as a marketer 
                      selling a product. The psychological difference is crucial for authentic 
                      recommendations to people you actually want to help.
                    </p>
                  </div>
                </div>

                <div className="flex items-start">
                  <div className="bg-Tonstores-green/10 rounded-full p-2 mr-3 mt-0.5">
                    <Award className="h-5 w-5 text-Tonstores-green" />
                  </div>
                  <div>
                    <h3 className="font-medium dark:text-white">Value-Align Promotion</h3>
                    <p className="text-gray-700 dark:text-gray-300">
                      Don't do hard sells – do value-aligned recommendations. Focus on the problems 
                      that Tonstores solves for builders, particularly the independence from exploitative 
                      platforms and ownership of customer data.
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-8">
          <Card>
            <CardHeader>
              <CardTitle className="text-xl dark:text-white">Recognition System</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600 dark:text-gray-400 text-sm mb-6">
                Our recognition system highlights infrastructure advocates in the community. 
                These badges represent more than just activity – they reflect your contribution 
                to building the ecosystem.
              </p>
              
              <div className="space-y-4">
                {recognitionBadges.map((badge) => (
                  <RecognitionBadge 
                    key={badge.id}
                    title={badge.title}
                    description={badge.description}
                    icon={badge.icon}
                    status={badge.status}
                  />
                ))}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-xl dark:text-white">Affiliate Best Practices</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                <li className="flex items-start">
                  <div className="bg-Tonstores-green/10 rounded-full p-1 mr-3 mt-0.5">
                    <Award className="h-4 w-4 text-Tonstores-green" />
                  </div>
                  <span className="text-gray-700 dark:text-gray-300">Focus on builders facing platform dependency issues</span>
                </li>
                <li className="flex items-start">
                  <div className="bg-Tonstores-green/10 rounded-full p-1 mr-3 mt-0.5">
                    <Award className="h-4 w-4 text-Tonstores-green" />
                  </div>
                  <span className="text-gray-700 dark:text-gray-300">Share your own story of gaining independence</span>
                </li>
                <li className="flex items-start">
                  <div className="bg-Tonstores-green/10 rounded-full p-1 mr-3 mt-0.5">
                    <Award className="h-4 w-4 text-Tonstores-green" />
                  </div>
                  <span className="text-gray-700 dark:text-gray-300">Emphasize the infrastructure, not just the tool</span>
                </li>
                <li className="flex items-start">
                  <div className="bg-Tonstores-green/10 rounded-full p-1 mr-3 mt-0.5">
                    <Award className="h-4 w-4 text-Tonstores-green" />
                  </div>
                  <span className="text-gray-700 dark:text-gray-300">Provide value before asking for referral</span>
                </li>
                <li className="flex items-start">
                  <div className="bg-Tonstores-green/10 rounded-full p-1 mr-3 mt-0.5">
                    <Award className="h-4 w-4 text-Tonstores-green" />
                  </div>
                  <span className="text-gray-700 dark:text-gray-300">Stay engaged with your referred builders</span>
                </li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default AffiliateTermsPage;